### ISSUE TITLE
Zły test

### ISSUE THREAD

**Issue by Shonsu** [SamouczekProgramisty/KursJava#1]
Jeśli jeśli dobrze rozumiem, to jeśli cena pierwszego itemu będzie większa od drugiego to test nie przejdzie, a powinien.
https://github.com/SamouczekProgramisty/KursJava/blob/86c1167200180033586ff4519807548603ddd745/22_testy_jednostkowe/src/test/java/pl/samouczekprogramisty/kursjava/shop/exercise/ItemTest.java#L38

można poprawić return w metodzie compareTo w klasie Item na:
return Double.compare(this.getPrice(), o.getPrice())!=0?-1:-1;

**Comment by kbl** [comment]
Jeśli cena pierwszego elementu będzie większa niż druga wówczas `compareTo` powinno zwrócić `1`.  Ten konkretny test jednostkowy sprawdza odwrotny przypadek, w którym pierwszy element jest mniejszy niż drugi i `compareTo` poprawnie zwraca wartość `-1`.
